# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    lane :ci_build do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    increment_build_number({
      build_number: latest_testflight_build_number(api_key_path: "api_key.json", app_identifier: "com.jmelitski.USGS") + 1
    })
    
    build_app(
        scheme: "USGS",
        output_name: "USGS.ipa",
    )
  end

  lane :ci_pilot do
    pilot(
      app_identifier: "com.jmelitski.USGS",
      api_key_path: "api_key.json",
      ipa: "USGS.ipa",
      changelog: "Test experimental features of Streamside",
      beta_app_description: "Test experimental features of Streamside",
      beta_app_feedback_email: "jonathanmelitski@gmail.com"
    )
  end

end
