name: CI

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Select Xcode 16
        # https://stackoverflow.com/questions/65821440/how-to-select-xcode-version-in-fastlane-when-using-github-actions
        run: sudo xcode-select -s '/Applications/Xcode_16.4.app/Contents/Developer'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-     
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      - name: Create fastlane API key json from updated key
        run: echo ${{ secrets.APP_STORE_CONNECT_API }} | base64 --decode > AuthKey_ZDBJYHK8BH.p8
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.B64_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.B64_MAIN_DISTRIBUTION }}
          BUILD_PROVISION_PROFILE_WIDGET_BASE64: ${{ secrets.B64_WIDGET_DISTRIBUTION }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=./build_pp.mobileprovision
          PP_WIDGET_PATH=./build_pp_widget.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode > "$CERTIFICATE_PATH"
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > "$PP_PATH"
          echo -n "$BUILD_PROVISION_PROFILE_WIDGET_BASE64" | base64 --decode > "$PP_WIDGET_PATH"

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_WIDGET_PATH ~/Library/MobileDevice/Provisioning\ Profiles 
      - name: Build app
        run: bundle exec fastlane ci_build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: USGS.ipa
  upload:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: macos-15
    steps:
      - name: Select Xcode 26
        # https://stackoverflow.com/questions/65821440/how-to-select-xcode-version-in-fastlane-when-using-github-actions
        run: sudo xcode-select -s '/Applications/Xcode_26.0.app/Contents/Developer'
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      - name: Create fastlane API key json from updated key
        run: echo ${{ secrets.APP_STORE_CONNECT_API }} | base64 --decode > AuthKey_ZDBJYHK8BH.p8
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Upload to TestFlight
        run: bundle exec fastlane ci_pilot
  cleanup:
    runs-on: macos-15
    needs: [build, upload]
    if: always()
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: build
